export const menu = [
  {
    id: 1,
    category: "Starters",
    list: [
      {
        id: 1,
        name: "Tomato Toast",
        regularPrice: "29",
        ingredients: [
          "Tomatillo",
          "Fried Okra",
          "Baja",
          "Crema",
          "Cabbage",
          "Baja",
        ],
        image: "/tomatoToast.png",
      },
      {
        id: 2,
        name: "Noodle Soup",
        regularPrice: "8.00",
        discountedPrice: "5.00",
        ingredients: [
          "Tomatillo",
          "Fried Okra",
          "Baja",
          "Crema",
          "Cabbage",
          "Baja",
        ],
        image: "/noodleSoup.png",
      },
      {
        id: 3,
        name: "Pumpkin Soup",
        regularPrice: "5.00",
        ingredients: [
          "Tomatillo",
          "Fried Okra",
          "Baja",
          "Crema",
          "Cabbage",
          "Baja",
        ],
        image: "/pumpkinSoup.png",
      },
    ],
  },
  {
    id: 2,
    category: "Breakfast",
    list: [
      {
        id: 1,
        name: "Delicious Pancakes",
        regularPrice: "8.00",
        discountedPrice: "5.00",
        ingredients: [
          "Tomatillo",
          "Fried Okra",
          "Baja",
          "Crema",
          "Cabbage",
          "Baja",
        ],
        image: "/deliciousPancakes.png",
      },
      {
        id: 2,
        name: "Sweet Heaven",
        regularPrice: "5.00",
        ingredients: [
          "Tomatillo",
          "Fried Okra",
          "Baja",
          "Crema",
          "Cabbage",
          "Baja",
        ],
        image: "/sweetHeaven.png",
      },
      {
        id: 3,
        name: "Oatmeal Spirit",
        regularPrice: "5.00",
        ingredients: [
          "Tomatillo",
          "Fried Okra",
          "Baja",
          "Crema",
          "Cabbage",
          "Baja",
        ],
        image: "/oatmealSpirit.png",
      },
      {
        id: 4,
        name: "Avocado Smash",
        regularPrice: "5.00",
        ingredients: [
          "Tomatillo",
          "Fried Okra",
          "Baja",
          "Crema",
          "Cabbage",
          "Baja",
        ],
        image: "/avocadoSmash.png",
      },
    ],
  },
  {
    id: 3,
    category: "Dinner",
    list: [
      {
        id: 1,
        name: "Italian Pizza",
        regularPrice: "5.00",
        ingredients: [
          "Tomatillo",
          "Fried Okra",
          "Baja",
          "Crema",
          "Cabbage",
          "Baja",
        ],
        image: "/italianPizza.png",
      },
      {
        id: 2,
        name: "Sea Curry",
        regularPrice: "8.00",
        discountedPrice: "5.00",
        ingredients: [
          "Tomatillo",
          "Fried Okra",
          "Baja",
          "Crema",
          "Cabbage",
          "Baja",
        ],
        image: "/seaCurry.png",
      },
      {
        id: 3,
        name: "Vegan Burger",
        regularPrice: "5.00",
        ingredients: [
          "Tomatillo",
          "Fried Okra",
          "Baja",
          "Crema",
          "Cabbage",
          "Baja",
        ],
        image: "/veganBurger.png",
      },
      {
        id: 4,
        name: "Noodle Bowl",
        regularPrice: "5.00",
        ingredients: [
          "Tomatillo",
          "Fried Okra",
          "Baja",
          "Crema",
          "Cabbage",
          "Baja",
        ],
        image: "/noodleBowl.png",
      },
    ],
  },
  {
    id: 4,
    category: "Drinks",
    list: [
      {
        id: 1,
        name: "Panthouse Tonic",
        regularPrice: "5.00",
        ingredients: [
          "Tomatillo",
          "Fried Okra",
          "Baja",
          "Crema",
          "Cabbage",
          "Baja",
        ],
        image: "/panthouseTonic.png",
      },
      {
        id: 2,
        name: "Apple Breeze",
        regularPrice: "8.00",
        discountedPrice: "5.00",
        ingredients: [
          "Tomatillo",
          "Fried Okra",
          "Baja",
          "Crema",
          "Cabbage",
          "Baja",
        ],
        image: "/appleBreeze.png",
      },
      {
        id: 3,
        name: "Frenchman Blitz",
        regularPrice: "5.00",
        ingredients: [
          "Tomatillo",
          "Fried Okra",
          "Baja",
          "Crema",
          "Cabbage",
          "Baja",
        ],
        image: "/frenchmanBlitz.png",
      },
    ],
  },
];

export const classes = [
  {
    id: 1,
    name: "Asian",
    category: "Delicious Breakfast",
    image: "/classDeliciousBreakfast.png",
    date: "June 16, 2023",
  },
  {
    id: 2,
    name: "Breakfast",
    category: "Coffee Time",
    image: "/classCoffeeTime.png",
    date: "March 17, 2023",
  },
  {
    id: 3,
    name: "Vegan",
    category: "Vegan Burger",
    image: "/classVeganBurger.png",
    date: "January 10, 2023",
  },
  {
    id: 4,
    name: "Italian",
    category: "Salad Style",
    image: "/classSaladStyle.png",
    date: "November 19, 2022",
  },
  {
    id: 5,
    name: "Italian",
    category: "Homemade Honey",
    image: "/classHomemadeHoney.png",
    date: "October 8, 2022",
  },
];
